export const LOAD_MOVIES_SUCCESS = "LOAD_MOVIES_SUCCESS";
export const LOAD_GENRES_SUCCESS = "LOAD_GENRES_SUCCESS";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAILURE = "DELETE_MOVIE_FAILURE";
export const RELOAD_MOVIES = "RELOAD_MOVIES";
